name: Deploy to Azure
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: |
          . 
          !venv/
          
    - name: Deploy to Azure Web Apps
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'saksikan-web'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
